# Generated by Django 2.2.24 on 2025-02-07 18:05

from django.db import migrations
import phonenumbers


def normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(parsed_number):
                flat.owner_pure_phone = phonenumbers.format_number(
                    parsed_number, phonenumbers.PhoneNumberFormat.E164
                )
                flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phones),
    ]
