# Generated by Django 2.2.24 on 2025-02-09 20:03

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20250208_2152'),
    ]

    operations = [
        migrations.RunPython(transfer_owners)
    ]
