# Generated by Django 2.2.24 on 2025-02-11 08:16

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250209_2303'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats),
    ]
